-- -- Insert doctors (unchanged)
-- INSERT INTO doctors (doctor_id, department, email, first_name, last_name, phone_number, specialization)
-- VALUES (1, 'Cardiology', 'doc1@example.com', 'John', 'Doe', '123-456-7890', 'Cardiologist'),
--        (2, 'Neurology', 'doc2@example.com', 'Alice', 'Smith', '321-654-0987', 'Neurologist'),
--        (3, 'Pediatrics', 'doc3@example.com', 'Mark', 'Brown', '111-222-3333', 'Pediatrician'),
--        (4, 'Oncology', 'doc4@example.com', 'Jane', 'Miller', '444-555-6666', 'Oncologist');
--
-- -- Insert patients (unchanged)
-- INSERT INTO patients (patient_id, address, date_of_birth, email, first_name, gender, last_name, phone_number)
-- VALUES (1, '123 Main St', '1985-04-23', 'patient1@example.com', 'Bob', 'Male', 'Johnson', '555-1234'),
--        (2, '456 Oak Rd', '1990-10-10', 'patient2@example.com', 'Sara', 'Female', 'Williams', '555-5678'),
--        (3, '789 Pine Ln', '1978-07-15', 'patient3@example.com', 'Tom', 'Male', 'Clark', '555-8765'),
--        (4, '101 Maple Ave', '2001-01-01', 'patient4@example.com', 'Lucy', 'Female', 'Davis', '555-4321');
--
-- -- Insert cases - FIXED (added is_public column)
-- INSERT INTO cases (case_id, doctor_id, patient_id, allergies, blood_type, created_at, description, status,
--                    treatment_plan, updated_at, is_public)
-- VALUES (1, 1, 1, 'Penicillin', 'A+', NOW(), 'Chest pain and shortness of breath', 'ACTIVE', 'Beta blockers and rest',
--         NOW(), false),
--        (2, 2, 2, NULL, 'B-', NOW(), 'Frequent migraines', 'ON_HOLD', 'MRI and neuro consult', NOW(), true),
--        (3, 3, 3, 'None', 'O+', NOW(), 'Childhood asthma flare', 'CLOSED', 'Inhaled corticosteroids', NOW(), false),
--        (4, 4, 4, 'Latex', 'AB+', NOW(), 'Abnormal blood test', 'ACTIVE', 'Biopsy and follow-up', NOW(), true);
--
-- -- Insert examinations (unchanged)
-- INSERT INTO examinations (examination_id, case_id, examination_date, examination_type, findings, notes, results,
--                           vital_signs)
-- VALUES (1, 1, NOW(), 'ECG', 'ST elevation', 'Patient experienced dizziness', 'Possible myocardial infarction', '{
--   "bp": "120/80",
--   "hr": 88
-- }'),
--        (2, 2, NOW(), 'CT Scan', 'No abnormalities detected', 'Headache persists', 'Negative scan', '{
--          "bp": "115/75",
--          "hr": 72
--        }'),
--        (3, 3, NOW(), 'Pulmonary Function Test', 'Reduced FEV1', 'Coughing during exam', 'Moderate asthma', '{
--          "bp": "110/70",
--          "hr": 95
--        }'),
--        (4, 4, NOW(), 'Blood Panel', 'Elevated WBC count', 'Suspect inflammation', 'Needs further evaluation', '{
--          "bp": "118/78",
--          "hr": 82
--        }'),
--        (5, 1, NOW(), 'Stress Test', 'Patient fatigued quickly', 'Needs cardiology follow-up', 'Positive stress test', '{
--          "bp": "130/85",
--          "hr": 110
--        }');
--
-- -- Insert forks (unchanged)
-- INSERT INTO forks (id, case_id, doctor_id, alternative_diagnosis, alternative_treatment, analysis_notes,
--                    fork_description, fork_title, recommendations)
-- VALUES (1, 1, 2, 'Angina', 'Nitrates and lifestyle change', 'Symptoms not entirely consistent with MI',
--         'Alternative view on chest pain', 'Alternate MI Diagnosis', 'Schedule stress test'),
--        (2, 2, 1, 'Tension headache', 'Painkillers and rest', 'History of stress-related issues',
--         'Alternative to migraines', 'Headache Differential', 'Psych consult'),
--        (3, 3, 4, 'Bronchitis', 'Antibiotics and fluids', 'Wheezing could indicate infection',
--         'Possible misdiagnosis of asthma', 'Asthma vs Bronchitis', 'Reassess if condition worsens'),
--        (4, 4, 3, 'Viral infection', 'Monitor and retest', 'Elevated WBC may not be cancer',
--         'Caution against premature biopsy', 'Blood Abnormality Recheck', 'Repeat labs in 1 week');
--
-- -- Cases with PII - FIXED (added is_public)
-- INSERT INTO cases (case_id, doctor_id, patient_id, allergies, blood_type, created_at, description, status,
--                    treatment_plan, updated_at, is_public)
-- VALUES (10, 1, 1, 'Penicillin', 'A+', NOW(),
--         'Patient Bob Johnson (DOB: 1985-04-23) reported severe chest pain and shortness of breath.',
--         'ACTIVE',
--         'Administer beta blockers and monitor vitals.', NOW(), false),
--
--        (11, 2, 2, NULL, 'B-', NOW(),
--         'Sara Williams reported migraines and sensitivity to light. Lives at 456 Oak Rd.',
--         'ON_HOLD',
--         'Schedule MRI and follow-up neurology consult.', NOW(), true),
--
--        (12, 3, 3, 'None', 'O+', NOW(),
--         'Tom Clark (email: patient3@example.com) showed signs of asthma during exercise.',
--         'CLOSED',
--         'Prescribe inhaled corticosteroids and schedule check-up.', NOW(), false);
--
-- -- Examinations with PII (unchanged)
-- INSERT INTO examinations (examination_id, case_id, examination_date, examination_type, findings, notes, results,
--                           vital_signs)
-- VALUES (101, 10, NOW(), 'ECG',
--         'Findings suggest myocardial infarction. Patient name: Bob Johnson.',
--         'Bob''s wife mentioned past cardiac history in the family.',
--         'ST elevation observed, recommend ICU admission.',
--         '{
--           "bp": "130/90",
--           "hr": 98
--         }'),
--
--        (102, 11, NOW(), 'CT Scan',
--         'Patient Sara appears anxious. Noted stress levels high.',
--         'Sara works night shifts; likely sleep-deprived.',
--         'No structural issues found.',
--         '{
--           "bp": "115/75",
--           "hr": 70
--         }'),
--
--        (103, 12, NOW(), 'Pulmonary Test',
--         'Tom reported wheezing while jogging. Mentioned previous ER visit at age 10.',
--         'Parent confirmed history of childhood asthma.',
--         'FEV1 below normal range.',
--         '{
--           "bp": "120/80",
--           "hr": 88
--         }');