CREATE TABLE users
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                      VARCHAR(100)                            NOT NULL,
    password                   VARCHAR(255)                            NOT NULL,
    first_name                 VARCHAR(50)                             NOT NULL,
    last_name                  VARCHAR(50)                             NOT NULL,
    phone_number               VARCHAR(20),
    role                       VARCHAR(255)                            NOT NULL,
    is_enabled                 BOOLEAN                                 NOT NULL,
    is_account_non_expired     BOOLEAN                                 NOT NULL,
    is_account_non_locked      BOOLEAN                                 NOT NULL,
    is_credentials_non_expired BOOLEAN                                 NOT NULL,
    created_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                 TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE doctors
    ADD CONSTRAINT FK_DOCTORS_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES users (id);

ALTER TABLE patients
    ADD CONSTRAINT FK_PATIENTS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES users (id);

ALTER TABLE doctors
    DROP COLUMN email;

ALTER TABLE doctors
    DROP COLUMN first_name;

ALTER TABLE doctors
    DROP COLUMN last_name;

ALTER TABLE doctors
    DROP COLUMN phone_number;

ALTER TABLE patients
    DROP COLUMN email;

ALTER TABLE patients
    DROP COLUMN first_name;

ALTER TABLE patients
    DROP COLUMN last_name;

ALTER TABLE patients
    DROP COLUMN phone_number;