spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/case-management
    username: sorsix
    password: sorsix

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

  ai:
    openai:
      api-key: ${GRK_API_KEY}
      base-url: "https://api.groq.com/openai"
      chat:
        options:
          model: meta-llama/llama-4-scout-17b-16e-instruct

app:
  jwt:
    secret: vG2rIzHz5FeXtwgxwK6r9IhXq98k3yQh6rriIS8V0bwHOiQAebgo6PEqelrWypjh
    expiration: 86400000 # 24 hours in milliseconds
